[package]
name = "main"
version = "0.1.0"
authors = ["Nassim Demirel Yassine"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ppm = { path = "../ppm" }